statement_parser:
    csv_columns:
        payment_party: "Name Zahlungsbeteiligter"
        amount: "Betrag"
        type_of_transfer: "Buchungstext"
        description: "Verwendungszweck"
        date: "Buchungstag"

    date_format: "%d.%m.%Y"

category_mapping:
    SAVINGS:
        payment_party: ["andreas rottach"]
    SALERY:
        description: ["lohn", "gehalt"]
    INSURANCE:
        payment_party: ["versicherung", "assuranc"]
    MOBILITY:
        or:
            description: ["tank", "park", "garage", "autohaus", "autocenter"]
            payment_party:
                ["tank", "bundeskasse in weiden", "vergoelst", "shell"]
    HOUSHOLD:
        payment_party: ["swu", "vodafone", "klarmobil"]
    GROCERIES:
        or:
            description: ["rewe", "finkbeiner", "takeaway", "lidl"]
            payment_party: ["lidl", "rewe", "finkbeiner", "ecenter", "drogerie"]
    RENT:
        description: ["miet"]
    ONLINE_SHOPPING:
        description: ["paypal", "amazon"]
