statement_parser:
    csv_columns:
        payment_party: "Name Zahlungsbeteiligter"
        amount: "Betrag"
        type_of_transfer: "Buchungstext"
        description: "Verwendungszweck"
        date: "Buchungstag"

    date_format: "%d.%m.%Y"

category_mapping:
    SAVINGS:
        sender: ["andreas rottach"]
    SALERY:
        desc: ["lohn", "gehalt"]
    INSURANCE:
        sender: ["versicherung", "assuranc"]
    MOBILITY:
        or:
            desc: ["tank", "park", "garage", "autohaus", "autocenter"]
            sender: ["tank", "bundeskasse in weiden", "vergoelst", "shell"]
    HOUSHOLD:
        or:
            desc: ["miet", "rewe", "finkbeiner", "takeaway", "lidl"]
            sender:
                [
                    "lidl",
                    "rewe",
                    "finkbeiner",
                    "ecenter",
                    "swu",
                    "drogerie",
                    "vodafone",
                    "klarmobil",
                ]
