statement_parser:
    csv_columns:
        payment_party: "Name Zahlungsbeteiligter"
        amount: "Betrag"
        type_of_transfer: "Buchungstext"
        description: "Verwendungszweck"
        date: "Buchungstag"

    date_format: "%d.%m.%Y"

    internal_transfer_categories: ["Savings"]

category_mapping:
    Salery:
        description: ["lohn", "gehalt"]
    Insurance:
        payment_party: ["versicherung", "assuranc"]
    Mobility:
        or:
            description: ["tank", "park", "garage", "autohaus", "autocenter"]
            payment_party:
                ["tank", "bundeskasse in weiden", "vergoelst", "shell", "aral"]
    Household:
        payment_party: ["swu"]
    Multimedia/Internet:
        or:
            description: ["spotify"]
            payment_party:
                ["vodafone", "klarmobil", "Rundfunk ARD, ZDF, DRadio"]
    Groceries:
        or:
            description: ["takeaway.com", "lidl", "kfc", "ristorante"]
            payment_party:
                [
                    "lidl",
                    "rewe",
                    "finkbeiner",
                    "ecenter",
                    "drogerie",
                    "kaufland",
                ]
    Rent:
        description: ["miet"]
    Online Shopping:
        or:
            description: ["paypal", "amazon"]
            payment_party: ["paypal", "amazon"]
    Dept:
        payment_party: ["florian rottach"]
    Shared Account:
        description: ["IBAN: DE601203000010813"]
    Savings:
        payment_party: ["andreas rottach"]
